Added concept of sendtmpl and added task subcommand/template

diff --git a/src/slack b/src/slack
--- a/src/slack
+++ b/src/slack
@@ -4,24 +4,24 @@ case "${1}" in
   init)
     while (( "$#" )); do
       case "${2}" in
-        --channel=*) CHANNEL=${2/--channel=/''} && shift ;;
-        --emoji=*) EMOJI=${2/--emoji=/''} && shift ;;
-        --silent) SILENT='0' && shift ;;
-        --username=*) USERNAME=${2/--username=/''} && shift ;;
-        --webhook=*) WEBHOOK=${2/--webhook=/''} && shift ;;
-        -c*) CHANNEL=${3} && shift && shift ;;
-        -e*) EMOJI=${3} && shift && shift ;;
-        -s) SILENT='0' && shift ;;
-        -u*) USERNAME=${3} && shift && shift ;;
-        -e*) WEBHOOK=${3} && shift && shift ;;
+        --channel=*) CHANNEL=${2/--channel=/''} ; shift ;;
+        --emoji=*) EMOJI=${2/--emoji=/''} ; shift ;;
+        --silent) SILENT='0' ; shift ;;
+        --username=*) USERNAME=${2/--username=/''} ; shift ;;
+        --webhook=*) WEBHOOK=${2/--webhook=/''} ; shift ;;
+        -c*) CHANNEL=${3} ; shift ; shift ;;
+        -e*) EMOJI=${3} ; shift ; shift ;;
+        -s) SILENT='0' ; shift ;;
+        -u*) USERNAME=${3} ; shift ; shift ;;
+        -w*) WEBHOOK=${3} ; shift ; shift ;;
         *) shift ;;
       esac
     done
 
-    test -z "${WEBHOOK}" && read -e -p 'Enter default webhook (e.g. https://hooks.slack.com/services/XXX/XXX/XXX): ' WEBHOOK
-    test -z "${CHANNEL}" && read -e -p 'Enter default channel (e.g. @username): ' CHANNEL
-    test -z "${USERNAME}" && read -e -p 'Enter default username (e.g. username-bot): ' USERNAME
-    test -z "${EMOJI}" && read -e -p 'Enter default emoji (e.g. :robot_face:): ' EMOJI
+    test -z "${WEBHOOK}" && read -e -p 'Enter webhook (e.g. https://hooks.slack.com/services/XXX/XXX/XXX): ' WEBHOOK
+    test -z "${USERNAME}" && read -e -p 'Enter username (e.g. username-bot): ' USERNAME
+    test -z "${EMOJI}" && read -e -p 'Enter emoji (e.g. :robot_face:): ' EMOJI
+    test -z "${CHANNEL}" && read -e -p 'Enter default channel (e.g. #general): ' CHANNEL
     test -z "${SILENT}" && echo -n 'Initializing: '
 
     echo "${WEBHOOK}" > ~/.slack-cli && \
@@ -43,26 +43,17 @@ case "${1}" in
 
     while (( "$#" )); do
       case "${2}" in
-        --channel=*) CHANNEL=${2/--channel=/''} && shift ;;
-        --emoji=*) EMOJI=${2/--emoji=/''} && shift ;;
-        --silent) SILENT='0' && shift ;;
-        --text=*) TEXT=${2/--text=/''} && shift ;;
-        --username=*) USERNAME=${2/--username=/''} && shift ;;
-        --webhook=*) WEBHOOK=${2/--webhook=/''} && shift ;;
-        -c*) CHANNEL=${3} && shift && shift ;;
-        -e*) EMOJI=${3} && shift && shift ;;
-        -s) SILENT='0' && shift ;;
-        -t*) TEXT=${3} && shift && shift ;;
-        -u*) USERNAME=${3} && shift && shift ;;
-        -e*) WEBHOOK=${3} && shift && shift ;;
+        --channel=*) CHANNEL=${2/--channel=/''} ; shift ;;
+        --silent) SILENT='0' ; shift ;;
+        --text=*) TEXT=${2/--text=/''} ; shift ;;
+        -c*) CHANNEL=${3} ; shift ; shift ;;
+        -s) SILENT='0' ; shift ;;
+        -t*) TEXT=${3} ; shift ; shift ;;
         *) test -n "${2}" && TEXT=${2} ; shift ;;
       esac
     done
 
-    test -z "${WEBHOOK}" && read -e -p 'Enter webhook url: ' WEBHOOK
     test -z "${CHANNEL}" && read -e -p 'Enter channel (e.g. #general): ' CHANNEL
-    test -z "${USERNAME}" && read -e -p 'Enter username (e.g. username-bot): ' USERNAME
-    test -z "${EMOJI}" && read -e -p 'Enter emoji (e.g. robot_face): ' EMOJI
     test -z "${TEXT}" && read -e -p 'Enter text (e.g. Hello World!): ' TEXT
     test -z "${SILENT}" && echo -n 'Sending: '
 
@@ -75,20 +66,65 @@ case "${1}" in
     esac
   ;;
 
+  sendtmpl)
+    CHANNEL=$(sed -n '2p' < ~/.slack-cli)
+    EMOJI=$(sed -n '4p' < ~/.slack-cli)
+    USERNAME=$(sed -n '3p' < ~/.slack-cli)
+    WEBHOOK=$(sed -n '1p' < ~/.slack-cli)
+
+    case "${2}" in
+      task)
+        COLOR='good'
+
+        while (( "$#" )); do
+          case "${3}" in
+            --channel=*) CHANNEL=${3/--channel=/''} ; shift ;;
+            --color=*) COLOR=${3/--color=/''} ; shift ;;
+            --silent) SILENT='0' ; shift ;;
+            --what=*) WHAT=${3/--what=/''} ; shift ;;
+            --when=*) WHEN=${3/--when=/''} ; shift ;;
+            --who=*) WHO=${3/--who=/''} ; shift ;;
+            -c*) CHANNEL=${4} ; shift ; shift ;;
+            -s) SILENT='0' ; shift ;;
+            *) shift ;;
+          esac
+        done
+
+        test -z "${CHANNEL}" && read -e -p 'Enter channel (e.g. #general): ' CHANNEL
+        test -z "${WHAT}" && read -e -p 'Enter what (e.g. Restarting server): ' WHAT
+        test -z "${WHO}" && read -e -p 'Enter who (e.g. First Last): ' WHO
+        test -z "${WHEN}" && read -e -p 'Enter when (e.g. 15:45, Now): ' WHEN
+        test -z "${COLOR}" && read -e -p 'Enter color (e.g. good, warning, danger): ' COLOR
+        test -z "${SILENT}" && echo -n 'Sending: '
+
+        PAYLOAD="payload={\"attachments\": [{\"author_name\": \"Task Notification\", \"author_icon\": \"http://www.emoji-cheat-sheet.com/graphics/emojis/nut_and_bolt.png\", \"text\": \"${WHAT}\", \"color\": \"${COLOR}\", \"fields\": [{\"title\": \"Who\", \"value\": \"${WHO}\", \"short\": true}, {\"title\": \"When\", \"value\": \"${WHEN}\", \"short\": true}]}], \"channel\": \"${CHANNEL}\", \"username\": \"${USERNAME}\", \"icon_emoji\": \"${EMOJI}\"}"
+        curl --silent --fail -X POST --data-urlencode "${PAYLOAD}" ${WEBHOOK} > /dev/null
+
+        case "$?" in
+          0) test -z "${SILENT}" && echo 'done' ; exit 0 ;;
+          *) test -z "${SILENT}" && echo 'fail' ; exit 1 ;;
+        esac
+      ;;
+
+      *) ${0} --help && exit 1 ;;
+    esac
+  ;;
+
   --help)
     a=(${0//\// })
     bin=${a[${#a[@]}-1]}
 
     echo 'Usage:'
-    echo "  ${bin} init [--webhook|-w <webhook>] [--channel|-c <channel>] [--username|-u <username>] [--emoji|-e <emoji>] [--silent|-s]"
-    echo "  ${bin} send [--text|-t <text>] [--webhook|-w <webhook>] [--channel|-c <channel>] [--username|-u <username>] [--emoji|-e <emoji>] [--silent|-s]"
+    echo "  ${bin} init [--webhook|-w <webhook>] [--username|-u <username>] [--emoji|-e <emoji>] [--channel|-c <channel>] [--silent|-s]"
+    echo "  ${bin} send [--channel|-c <channel>] [--text|-t <text>]  [--silent|-s]"
+    echo "  ${bin} sendtmpl task [--channel|-c <channel>] [--what=<what>] [--who=<who>] [--when=<when>] [--color=<color>] [--silent|-s]"
     echo
     echo "Settings Commands:"
     echo "  init     Initialize default settings"
     echo
     echo "Messaging Commands:"
-    echo "  send           Send a message"
-    echo "  sendf task     Send a formatted message; task template"
+    echo "  send              Send a message"
+    echo "  sendtmpl task     Send a task templated message"
   ;;
 
   --version) echo 'v0.1.0' ;;
