Added output to all subcommands and added optional silent flag

diff --git a/src/slack b/src/slack
--- a/src/slack
+++ b/src/slack
@@ -2,19 +2,16 @@
 
 case "${1}" in
   init)
-    CHANNEL=
-    EMOJI=
-    USERNAME=
-    WEBHOOK=
-
     while (( "$#" )); do
       case "${2}" in
         --channel=*) CHANNEL=${2/--channel=/''} && shift ;;
         --emoji=*) EMOJI=${2/--emoji=/''} && shift ;;
+        --silent) SILENT='0' && shift ;;
         --username=*) USERNAME=${2/--username=/''} && shift ;;
         --webhook=*) WEBHOOK=${2/--webhook=/''} && shift ;;
         -c*) CHANNEL=${3} && shift && shift ;;
         -e*) EMOJI=${3} && shift && shift ;;
+        -s) SILENT='0' && shift ;;
         -u*) USERNAME=${3} && shift && shift ;;
         -e*) WEBHOOK=${3} && shift && shift ;;
         *) shift ;;
@@ -25,17 +22,22 @@ case "${1}" in
     test -z "${CHANNEL}" && read -e -p 'Enter default channel (e.g. @username): ' CHANNEL
     test -z "${USERNAME}" && read -e -p 'Enter default username (e.g. username-bot): ' USERNAME
     test -z "${EMOJI}" && read -e -p 'Enter default emoji (e.g. :robot_face:): ' EMOJI
+    test -z "${SILENT}" && echo -n 'Initializing: '
 
     echo "${WEBHOOK}" > ~/.slack-cli && \
     echo "${CHANNEL}" >> ~/.slack-cli && \
     echo "${USERNAME}" >> ~/.slack-cli && \
     echo "${EMOJI}" >> ~/.slack-cli
+
+    case "$?" in
+      0) test -z "${SILENT}" && echo 'done' ; exit 0 ;;
+      *) test -z "${SILENT}" && echo 'fail' ; exit 1 ;;
+    esac
   ;;
 
   send)
     CHANNEL=$(sed -n '2p' < ~/.slack-cli)
     EMOJI=$(sed -n '4p' < ~/.slack-cli)
-    MESSAGE=
     USERNAME=$(sed -n '3p' < ~/.slack-cli)
     WEBHOOK=$(sed -n '1p' < ~/.slack-cli)
 
@@ -44,11 +46,13 @@ case "${1}" in
         --channel=*) CHANNEL=${2/--channel=/''} && shift ;;
         --emoji=*) EMOJI=${2/--emoji=/''} && shift ;;
         --message=*) MESSAGE=${2/--message=/''} && shift ;;
+        --silent) SILENT='0' && shift ;;
         --username=*) USERNAME=${2/--username=/''} && shift ;;
         --webhook=*) WEBHOOK=${2/--webhook=/''} && shift ;;
         -c*) CHANNEL=${3} && shift && shift ;;
         -e*) EMOJI=${3} && shift && shift ;;
         -m*) MESSAGE=${3} && shift && shift ;;
+        -s) SILENT='0' && shift ;;
         -u*) USERNAME=${3} && shift && shift ;;
         -e*) WEBHOOK=${3} && shift && shift ;;
         *) test -n "${2}" && MESSAGE=${2} ; shift ;;
@@ -60,10 +64,15 @@ case "${1}" in
     test -z "${USERNAME}" && read -e -p 'Enter username (e.g. username-bot): ' USERNAME
     test -z "${EMOJI}" && read -e -p 'Enter emoji (e.g. robot_face): ' EMOJI
     test -z "${MESSAGE}" && read -e -p 'Enter message (e.g. Hello World!): ' MESSAGE
+    test -z "${SILENT}" && echo -n 'Sending: '
 
     PAYLOAD="payload={\"text\": \"${MESSAGE}\", \"channel\": \"${CHANNEL}\", \"username\": \"${USERNAME}\", \"icon_emoji\": \"${EMOJI}\"}"
+    curl --silent --fail -X POST --data-urlencode "${PAYLOAD}" ${WEBHOOK} > /dev/null
 
-    exec curl --silent --fail -X POST --data-urlencode "${PAYLOAD}" ${WEBHOOK} > /dev/null
+    case "$?" in
+      0) test -z "${SILENT}" && echo 'done' ; exit 0 ;;
+      *) test -z "${SILENT}" && echo 'fail' ; exit 1 ;;
+    esac
   ;;
 
   --help)
@@ -71,8 +80,8 @@ case "${1}" in
     bin=${a[${#a[@]}-1]}
 
     echo 'Usage:'
-    echo "  ${bin} init [--webhook|-w <webhook>] [--channel|-c <channel>] [--username|-u <username>] [--emoji|-e <emoji>]"
-    echo "  ${bin} send [--webhook|-w <webhook>] [--channel|-c <channel>] [--username|-u <username>] [--emoji|-e <emoji>] [--message|-m <message>]"
+    echo "  ${bin} init [--webhook|-w <webhook>] [--channel|-c <channel>] [--username|-u <username>] [--emoji|-e <emoji>] [--silent|-s]"
+    echo "  ${bin} send [--webhook|-w <webhook>] [--channel|-c <channel>] [--username|-u <username>] [--emoji|-e <emoji>] [--message|-m <message>] [--silent|-s]"
     echo
     echo "Settings Commands:"
     echo "  init     Initialize default settings"
